/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class MidiFormatter */

#ifndef _Included_MidiFormatter
#define _Included_MidiFormatter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MidiFormatter
 * Method:    parsiraj
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MidiFormatter_parsiraj
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
